### PR TITLE
Windows automatic building and python wheel CI

### PR DESCRIPTION
**Pull request by bboettcher3**
- Adds an automatic building batch file named `windows_build.bat` that will  bring in and build dependencies as well as libmapper
- Has CI build windows python wheel and upload artifacts

### CODE REVIEW

**Comment by malloch** [comment]
Thanks @bboettcher3 this looks great! Can we stick to pulling liblo from the main repo and patch the config file in your batch file instead of depending on a custom fork that might go out of sync later?

**Comment by bboettcher3** [comment]
> Thanks @bboettcher3 this looks great! Can we stick to pulling liblo from the main repo and patch the config file in your batch file instead of depending on a custom fork that might go out of sync later?

Yeah, it's a bit hacky right now, but I'm also a bit weary of linking to the liblo master branch in case it gets updated and breaks something. The newest liblo release tag doesn't contain [Johnty's commit](https://github.com/radarsat1/liblo/commit/ae12a22ab6c4c3fe81a3d76778e3acb765115cef) to fix building for windows, so I'm not sure what the best way to do this would be. Any suggestions? Editing the single line in the config file is pretty difficult to do in batch scripting as well, and might require even more hacks.

**Comment by malloch** [comment]
I managed to patch the config file in place by editing your script – see https://github.com/malloch/libmapper/tree/feat/windows_ci

The only other change I'd like to see before merging is running the test suite after building. On Linux/macOS we use `make tests` from the /test directory. Do you have time to add this to the CI script?

**Comment by bboettcher3** [comment]
> I managed to patch the config file in place by editing your script

Awesome, clever way of doing that!

> The only other change I'd like to see before merging is running the test suite after building. On Linux/macOS we use `make tests` from the /test directory. Do you have time to add this to the CI script?

Sure thing, I'll take care of that early this week and ping you when it's updated.

**Comment by bboettcher3** [comment]
@malloch just pushed a commit so that most (all but about 5) tests are built in the same cmake process as libmapper. The ones that are commented out from building just have a few compilation bugs I'm looking into. The rest are running fine when manually executed, but the posix signal method for exiting/evaluating won't work for windows. Any ideas for ways around this?

**Comment by bboettcher3** [comment]
@malloch only the cpp test is left, some errors due to a different CXX standard I think because the errors are in the compilation of mapper_cpp.h. What standard should we be using?
Also, the most recent CI works on my fork but times out on this one, I'm sure it would work if you want to rerun it. I don't have the permissions here.

**Comment by malloch** [comment]
@bboettcher3 I think you'll need C++14. Can you let me know more about the compilation errors?

Great progress!

**Comment by bboettcher3** [comment]
Here's one of the many related errors to give you an idea:
```
C:\Users\brady\Documents\GitHub\McGill\libmapper\include\mapper/mapper_cpp.h(578,30): error C2131: expression did not e
valuate to a constant [C:\Users\brady\Documents\GitHub\McGill\libmapper\build\test\testcpp.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\include\mapper/mapper_cpp.h(578,30): message : failure was caused by a
 read of a variable outside its lifetime [C:\Users\brady\Documents\GitHub\McGill\libmapper\build\test\testcpp.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\include\mapper/mapper_cpp.h(578,30): message : see usage of 'num_srcs'
 [C:\Users\brady\Documents\GitHub\McGill\libmapper\build\test\testcpp.vcxproj]
```

**Comment by malloch** [comment]
Looking into it... What version of VS are you using?

**Comment by bboettcher3** [comment]
> Looking into it... What version of VS are you using?

VS2019 built with windows sdk version 10.0.18362.0

**Comment by malloch** [comment]
@bboettcher3 Try pulling in main branch and try again – I made some tweaks to mapper_cpp.h

**Comment by bboettcher3** [comment]
> @bboettcher3 Try pulling in main branch and try again – I made some tweaks to mapper_cpp.h

Reduced the number of errors big time, only this left:
```
testcpp.obj : error LNK2019: unresolved external symbol mpr_time_cmp referenced in function "public: bool __cdecl mappe
r::Time::operator<(class mapper::Time &)" (??MTime@mapper@@QEAA_NAEAV01@@Z) [C:\Users\brady\Documents\GitHub\McGill\lib
mapper\build\test\testcpp.vcxproj]
C:\Users\brady\Documents\GitHub\McGill\libmapper\build\test\Debug\testcpp.exe : fatal error LNK1120: 1 unresolved exter
nals [C:\Users\brady\Documents\GitHub\McGill\libmapper\build\test\testcpp.vcxproj]
```
I'll look into it but posting in case you know what it might be from.

**Comment by malloch** [comment]
looks like you could just rename the "terminate" variable in testcpp.cpp

**Comment by bboettcher3** [comment]
I did, and updated the error in the message above with the new error

**Comment by malloch** [comment]
I just pushed the fix to main branch

**Comment by bboettcher3** [comment]
all building now!

**Comment by bboettcher3** [comment]
@malloch To fix the python wheel for windows two .py.in files had to be copied and named to just .py files. Someone on mac or linux should check that it doesn't break anything in the other wheels, because I'm not sure why .py.in files are needed aside from 
makefiles

**Comment by malloch** [comment]
@bboettcher3 under Linux/macOS the *.py.in files are copied to *.py by autoconf/make so your change doesn't work across platforms. Could you use your windows scripts to copy/rename the files during build instead?

**Comment by bboettcher3** [comment]
> Could you use your windows scripts to copy/rename the files during build instead?

It works with a rename for bindings/python/libmapper/mapper.py.in, but for bindings/python/setup.py.in there are some edits made to get it running for windows as well, since the .py.in file uses makefile variables like @PACKAGE_VERSION@ and @SO_EXT@.

We need to address the multiple build configs first I think, otherwise we'll have multiple versions in different files that we'd have to synchronize every time.

**Comment by malloch** [comment]
There's [an example in the liblo repo of generating the version string using cmake](https://github.com/radarsat1/liblo/blob/master/cmake/CMakeLists.txt). Maybe this helps?

**Comment by bboettcher3** [comment]
@malloch I wasn't able to use cmake for parsing since the python files were the ones that needed the variable. I just made a regex for configure.ac to parse the version for both files, and it works for making the wheel. Let me know if you can test this on Linux/Mac to make sure it doesn't break anything, but it should be ok since it's separated with platform checks.

**Pull request merged**
